feat: implemented test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,16 +3,65 @@ name: Fibonacci
 on:
   push:
     branches: master
-    
+
 jobs:
   build:
     runs-on: ubuntu-22.04
-    permissions: 
+    permissions:
       packages: write
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+      - name: Test-Fibonacci
+        run: |
+          # Ensuring the script in executable
+          chmod +x fibo.sh
+
+          # Test case 1: 
+          echo "Running Test-1: valid input (30)"
+          echo 30 | ./fibo.sh > file.txt
+          if grep -q "832040" file.txt; then
+            echo "Test-1 passed"
+          else
+            echo "Test-1 failed" && exit 1
+          fi
+
+          # Test case 2:
+          echo "Running Test-2: valid input (115)"
+          echo 115 | ./fibo.sh > file.txt
+          if grep -q "483162952612010163284885" file.txt; then
+            echo "Test-2 passed"
+          else
+            echo "Test-2 failed" && exit 2
+          fi
+
+          # Test case 3:
+          echo "Running Test-3: out-of-range (-1)"
+          echo -1 | ./fibo.sh | head -n 1  > file.txt
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
+            echo "Test-3 passed"
+          else
+            echo "Test-3 failed" && exit 3
+          fi
+
+          # Test case 4:
+          echo "Running Test-4: out-of-range (501)"
+          echo 501 | ./fibo.sh | head -n 1 > file.txt
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
+            echo "Test-4 passed"
+          else
+            echo "Test-4 failed" && exit 4
+          fi
+
+          # Test case 5: 
+          echo "Running Test-5: Invalid Input (a)"
+          echo a | ./fibo.sh | head -n 1 > file.txt
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
+            echo "Test-5 passed"
+          else
+            echo "Test-5 failed" && exit 5
+          fi
 
       - name: Login to container registry
         uses: docker/login-action@v2
@@ -28,5 +77,4 @@ jobs:
           push: true
           tags: |
             ghcr.io/${{ github.repository }}:latest
-            ghcr.io/${{ github.repository }}:${{ github.run_number }}    
-    
+            ghcr.io/${{ github.repository }}:${{ github.run_number }}
